### ISSUE TITLE
selection.range.commonAncestorContainer Error in Safari

### ISSUE THREAD

**Issue by adamellsworth** [guardian/scribe-plugin-smart-lists#18]
OS X: 10.10.1 (14B25)
Safari: 8.0.2 (10600.2.5)

---

### Active Plugin/Versions (bower): 

    "dependencies": {
        "requirejs": "~2.1.15",
        "scribe": "~1.2.0",
        "scribe-plugin-toolbar": "~0.1.4",
        "scribe-plugin-formatter-plain-text-convert-new-lines-to-html": "~0.1.1",
        "scribe-plugin-sanitizer": "~0.1.6",
        "scribe-plugin-inline-styles-to-elements": "~0.1.1",
        "scribe-plugin-heading-command": "~0.1.0",
        "scribe-plugin-link-prompt-command": "~0.1.2",
        "scribe-plugin-blockquote-command": "~0.1.0",
        "scribe-plugin-curly-quotes": "~0.1.8",
        "scribe-plugin-intelligent-unlink-command": "~0.1.5",
        "scribe-plugin-smart-lists": "~0.1.6"
    }

---

### Usage:

    var ScribeManagerModule = (function () {
        
        // Scribe instance is globally scoped for this module so it can be
        // accessed by its other function
        var _scribe;
        
        return {
            initialize: function (scribeSelector, toolbarSelector) {
            
                    require({
                        paths: {
                            // paths go here, all loading fine
                        }
                    }, [
                        'scribe',
                        'scribe-plugin-toolbar',
                        'scribe-plugin-blockquote-command',
                        'scribe-plugin-curly-quotes',
                        'scribe-plugin-formatter-plain-text-convert-new-lines-to-html',
                        'scribe-plugin-heading-command',
                        'scribe-plugin-intelligent-unlink-command',
                        'scribe-plugin-link-prompt-command',
                        'scribe-plugin-sanitizer',
                        'scribe-plugin-smart-lists'
                    ], function (
                        Scribe,
                        scribePluginToolbar,
                        scribePluginBlockquoteCommand,
                        scribePluginCurlyQuotes,
                        scribePluginFormatterPlainTextConvertNewLinesToHtml,
                        scribePluginHeadingCommand,
                        scribePluginIntelligentUnlinkCommand,
                        scribePluginLinkPromptCommand,
                        scribePluginSanitizer,
                        scribePluginSmartLists
                    ) {
                        _scribe = new Scribe(document.querySelector(scribeSelector), {});

                        _scribe.use(scribePluginBlockquoteCommand());
                        _scribe.use(scribePluginHeadingCommand(2));
                        _scribe.use(scribePluginIntelligentUnlinkCommand());
                        _scribe.use(scribePluginLinkPromptCommand());
                        _scribe.use(scribePluginToolbar(document.querySelector(toolbarSelector)));
                        _scribe.use(scribePluginSmartLists());
                        _scribe.use(scribePluginCurlyQuotes());

                        // Formatters
                        _scribe.use(scribePluginSanitizer({
                            tags: {
                                p: {},
                                br: {},
                                b: {},
                                strong: {},
                                i: {},
                                strike: {},
                                blockquote: {},
                                ol: {},
                                ul: {},
                                li: {},
                                a: { href: true },
                                h2: {}
                            }
                        }));

                        _scribe.use(scribePluginFormatterPlainTextConvertNewLinesToHtml());
                    });
            }
        };
    })();

Then it's invoked via:

    ScribeManagerModule.initialize('#scribe', '#toolbar');

---

### Error 

    TypeError: undefined is not an object (evaluating 'selection.range.commonAncestorContainer')

Line Number

    ln. 76:         var container = selection.range.commonAncestorContainer;

---

### To reproduce: 

Initialize as denoted above and try to type a few characters into the newly assigned contenteditable/scribe div

---

### Notes
- Does not happen in FF or Chrome
- Does not occur if I comment it out: `// _scribe.use(scribePluginSmartLists());`

**Comment by hmgibson23** [comment]
Safari's not on our supported browser list, so you could submit a patch to https://github.com/guardian/scribe to enable Safari support.
